version: "3.7"
volumes:
  backend-node:
    driver: local
  pycache:
    driver: local
  dynamodb-data:
    driver: local
services:
  # front:
  #   build: ./front
  #   volumes:
  #     - ./front:/usr/src/app
  back:
    build: ./back
    volumes:
      - ./back:/usr/src/app
      - backend-node:/usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
  redis:
    image: redis
  dynamodb:
    image: amazon/dynamodb-local
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    entrypoint:
      - java
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    ports:
      - "8080:8080"
