version: "3.7"
volumes:
  back-node:
    driver: local
  dynamodb-data:
    driver: local
services:
  front:
    build: ./front
    restart: always
    volumes:
      - ./front:/usr/src/app
      # node_modulesはボリュームコンテナに置きたいが、エディタ上での開発の利便性のためにローカル環境にインストール
      # - front-node:/usr/src/app/node_modules
    ports:
      - "8080:8080"
  back:
    build: ./back
    restart: always
    volumes:
      - ./back:/usr/src/app
      - ./dynamodb/tables:/usr/src/app/config/dynamodb/tables
      - back-node:/usr/src/app/node_modules
    depends_on:
      - dynamodb
    ports:
      - "5000:5000"
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      DYNAMODB_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
      CORS_ORIGIN: "*"
  dynamodb:
    image: amazon/dynamodb-local
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    entrypoint:
      - java
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    ports:
      - "8000:8000"
