app: fun-done-learn
service: flask-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dynamodb-local

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
custom:
  wsgi:
    app: app.main.app
    packRequirements: false
  pythonRequirements:
    usePipenv: false

resources: # CloudFormation template syntax from here on.
  Resources:
    boards:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: boards
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
