app: fun-done-learn
service: flask-api

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
custom:
  wsgi:
    app: app.main.app
    packRequirements: false
    pythonBin: python3.8
